languageCode = "en-us"
title = "James Meakin"
baseurl = "https://meakin.nl/"
theme = "hugo-cactus-theme"
disqusShortname = "meakin-nl"
googleAnalytics = "UA-97109041-1"

[Params]
  name = "James Meakin"
  description = "description goes here"
  bio = "Research Software Engineer"
  twitter = "DrJamesMeakin"
  enableRSS = true

  # Sharing options and author information in posts
	aboutAuthor = "Research Software Engineer at Radboud University Medical Center."
	tweet = ""
	share = ""

  iconFont = "font-awesome"

[social]
  twitter = "https://twitter.com/DrJamesMeakin"
  github = "https://github.com/jmeakin"
  linkedin = "https://linkedin.com/in/jamesameakin"
