languageCode = "en-us"
title = "James Meakin"
baseurl = "https://www.jmsmkn.com/"
theme = "hugo-cactus-theme"
disqusShortname = "meakin-nl"
googleAnalytics = "UA-97109041-1"

[Params]
  name = "James Meakin"
  description = "description goes here"
  bio = "Research Software Engineer"
  twitter = "jmsmkn"
  enableRSS = true

  # Sharing options and author information in posts
	aboutAuthor = "Tech Lead, Research Software Engineering at Radboud UMC."
	tweet = ""
	share = ""

  iconFont = "font-awesome"

[social]
  twitter = "https://twitter.com/jmsmkn"
  github = "https://github.com/jmsmkn"
  linkedin = "https://linkedin.com/in/jamesameakin"

